use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde_json::{Map, Value, json};

use super::metadata::{ROLES, pick};

/// Heroic keys everything off app_name and uses it as a config file name, so
/// it has to be stable across runs and safe on a filesystem. The store id is
/// both, and prefixing it keeps these apart from anything Heroic adds itself.
fn app_name(store_id: &str) -> String {
    format!("xodus-{store_id}")
}

fn heroic_config_dir(explicit: Option<String>) -> Option<PathBuf> {
    if let Some(explicit) = explicit {
        return Some(PathBuf::from(explicit));
    }

    let home = PathBuf::from(std::env::var("HOME").ok()?);
    let config = std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| home.join(".config"));

    [
        config.join("heroic"),
        home.join(".var/app/com.heroicgameslauncher.hgl/config/heroic"),
    ]
    .into_iter()
    .find(|path| path.is_dir())
}

/// Heroic launches a native entry by running the executable directly, so the
/// thing it is pointed at is a script that hands the game back to xodus. It
/// lives beside the game so that Heroic's own uninstall, which deletes the
/// executable's directory, removes the right thing.
fn write_launcher(
    source: &Path,
    wine: &str,
    exe: Option<&str>,
    prefix: Option<&str>,
    title: &str,
) -> std::io::Result<PathBuf> {
    let path = source.join("xpedited-launch.sh");
    let cli = std::env::current_exe()
        .map(|path| path.display().to_string())
        .unwrap_or_else(|_| "xodus-cli".to_string());
    let prefix = prefix.unwrap_or("$HOME/.local/share/xpedited/prefix");

    let script = format!(
        "#!/usr/bin/env bash\n\
         # Generated by `xpedited heroic` for {title}. Safe to regenerate.\n\
         set -uo pipefail\n\
         \n\
         XPEDITED_CLI=${{XPEDITED_CLI:-{cli}}}\n\
         XPEDITED_WINE=${{XPEDITED_WINE:-{wine}}}\n\
         export WINEPREFIX=${{WINEPREFIX:-{prefix}}}\n\
         \n\
         exec \"$XPEDITED_CLI\" run {source} \"$XPEDITED_WINE\"{exe}\n",
        title = title,
        cli = cli,
        wine = wine,
        prefix = prefix,
        source = shell_quote(&source.display().to_string()),
        exe = exe.map_or(String::new(), |exe| format!(" -e {}", shell_quote(exe))),
    );

    std::fs::write(&path, script)?;
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))?;
    Ok(path)
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Whether this product itself carries something we could run.
fn has_desktop_package(product: &xodus::models::displaycatalog::Product) -> bool {
    product.display_sku_availabilities.iter().any(|sku| {
        sku.sku.properties.packages.iter().any(|package| {
            package
                .platform_dependencies
                .iter()
                .any(|dep| dep.platform_name == "Windows.Desktop")
        })
    })
}

/// The products that satisfy this one. A Game Pass subscription SKU carries
/// no package of its own and names the real ones this way. Subscription
/// products are dropped - they are the tiers themselves, not a game - and so
/// is the product's own id, which every product lists.
fn satisfying_products(product: &xodus::models::displaycatalog::Product) -> Vec<String> {
    let mut out: Vec<String> = product
        .display_sku_availabilities
        .iter()
        .flat_map(|sku| sku.availabilities.iter())
        .flat_map(|availability| availability.licensing_data.iter())
        .flat_map(|licensing| licensing.satisfying_entitlement_keys.iter())
        .flat_map(|satisfies| satisfies.entitlement_keys.iter())
        .filter_map(|key| {
            let parts: Vec<&str> = key.split(':').collect();
            (parts.len() == 3 && parts[0] == "big").then(|| parts[1].to_string())
        })
        .filter(|id| *id != product.product_id && !id.starts_with("CFQ7TT"))
        .collect();
    out.sort();
    out.dedup();
    out
}

/// Heroic will not let a sideload entry be installed through its UI: the
/// backend's install for that runner is an explicit "not implemented", and
/// the frontend refuses to even open the dialog for it. So every entry has
/// to claim to be installed or it could never be started at all, which
/// leaves nothing in the library itself to tell the two states apart.
///
/// Heroic's own custom categories do tell them apart, and they appear as
/// filters in its sidebar, so they are maintained here instead: one for what
/// is on disk, one for what will be fetched on first play.
const CATEGORY_READY: &str = "Xbox - downloaded";
const CATEGORY_PENDING: &str = "Xbox - downloads on first play";

fn sync_categories(heroic: &Path, library: &Value) -> std::io::Result<(usize, usize)> {
    let config_path = heroic.join("store").join("config.json");
    let mut config: Value = std::fs::read_to_string(&config_path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_else(|| Value::Object(Map::new()));
    if !config.is_object() {
        config = Value::Object(Map::new());
    }

    let empty = vec![];
    let (mut ready, mut pending) = (vec![], vec![]);
    for game in library["games"].as_array().unwrap_or(&empty) {
        let Some(name) = game["app_name"].as_str() else {
            continue;
        };
        if !name.starts_with("xodus-") {
            continue;
        }
        let on_disk = game["folder_name"]
            .as_str()
            .is_some_and(|folder| Path::new(folder).is_dir());
        if on_disk {
            ready.push(Value::String(name.to_string()));
        } else {
            pending.push(Value::String(name.to_string()));
        }
    }
    let counts = (ready.len(), pending.len());

    let games = config
        .as_object_mut()
        .expect("config is an object")
        .entry("games")
        .or_insert_with(|| Value::Object(Map::new()));
    if !games.is_object() {
        *games = Value::Object(Map::new());
    }
    let categories = games
        .as_object_mut()
        .expect("games is an object")
        .entry("customCategories")
        .or_insert_with(|| Value::Object(Map::new()));
    if !categories.is_object() {
        *categories = Value::Object(Map::new());
    }
    let categories = categories.as_object_mut().expect("categories is an object");
    // Anything the player has categorised by hand stays; only ours are rebuilt.
    categories.insert(CATEGORY_READY.to_string(), Value::Array(ready));
    categories.insert(CATEGORY_PENDING.to_string(), Value::Array(pending));

    std::fs::create_dir_all(config_path.parent().unwrap())?;
    let temporary = config_path.with_extension("json.tmp");
    let text = serde_json::to_string_pretty(&config).map_err(std::io::Error::other)?;
    std::fs::write(&temporary, text)?;
    std::fs::rename(&temporary, &config_path)?;
    Ok(counts)
}

/// Re-derive the categories from what is actually on disk. No network, so a
/// launcher can call it the moment a download finishes.
pub fn sync(config: Option<String>) -> ExitCode {
    let Some(heroic) = heroic_config_dir(config) else {
        eprintln!("could not find a Heroic configuration directory; pass --config");
        return ExitCode::FAILURE;
    };
    let library: Value = std::fs::read_to_string(heroic.join("sideload_apps").join("library.json"))
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_else(|| Value::Object(Map::new()));

    match sync_categories(&heroic, &library) {
        Ok((ready, pending)) => {
            println!("{ready} downloaded, {pending} not downloaded yet");
            ExitCode::SUCCESS
        }
        Err(err) => {
            eprintln!("could not update Heroic's categories: {err}");
            ExitCode::FAILURE
        }
    }
}

/// Whether the library already points this title at a game that is really on
/// disk. A catalogue pass must not repoint an installed title at an empty
/// directory and make the player download it again.
fn already_installed(library: &Value, name: &str) -> bool {
    let Some(games) = library.get("games").and_then(Value::as_array) else {
        return false;
    };
    games.iter().any(|game| {
        game["app_name"].as_str() == Some(name)
            && game["folder_name"]
                .as_str()
                .is_some_and(|folder| Path::new(folder).is_dir())
    })
}

/// Replace this game's entry in Heroic's sideload library, keeping every
/// other entry and any field Heroic has added to ours since.
fn upsert(library: &mut Value, entry: Value) {
    let games = library
        .as_object_mut()
        .expect("library is an object")
        .entry("games")
        .or_insert_with(|| Value::Array(vec![]));
    let Some(games) = games.as_array_mut() else {
        *games = Value::Array(vec![entry]);
        return;
    };

    let name = entry["app_name"].as_str().unwrap_or_default().to_string();
    match games
        .iter_mut()
        .find(|game| game["app_name"].as_str() == Some(name.as_str()))
    {
        Some(existing) => {
            let (Some(existing), Some(entry)) = (existing.as_object_mut(), entry.as_object())
            else {
                return;
            };
            for (key, value) in entry {
                existing.insert(key.clone(), value.clone());
            }
        }
        None => games.push(entry),
    }
}

pub async fn run(
    client: &reqwest::Client,
    source: String,
    wine: String,
    exe: Option<String>,
    market: Option<String>,
    prefix: Option<String>,
    config: Option<String>,
    dry_run: bool,
) -> ExitCode {
    let source = match std::fs::canonicalize(&source) {
        Ok(source) => source,
        Err(err) => {
            eprintln!("{source}: {err}");
            return ExitCode::FAILURE;
        }
    };

    let game_config = crate::gameconfig::read(&source);
    // Plenty of packages - most of the Unity ones - name no executable at
    // all. That is not a problem: only the game's own executable is kept
    // encrypted in the container, so `run` picks the right one on its own
    // when it is not told.
    let exe = exe.or_else(|| {
        game_config
            .as_deref()
            .and_then(|xml| crate::gameconfig::attr_value(xml, "Executable", "Name"))
    });

    let store_id = game_config.as_deref().and_then(crate::gameconfig::store_id);

    // The catalog is public, so art and a proper title come for free when we
    // know the store id. Without one we still have a launchable entry.
    let mut title = source
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "Xbox game".to_string());
    let mut description = String::new();
    let mut art_square = String::new();
    let mut art_cover = String::new();

    if let Some(store_id) = &store_id {
        match xodus::api::displaycatalog::find_products_by_id(
            client,
            store_id.clone(),
            market.unwrap_or("US".to_string()),
            vec!["en-US".to_string()],
        )
        .await
        {
            Ok(response) => {
                if let Some(props) = response.product.localized_properties.first() {
                    if !props.product_title.is_empty() {
                        title = props.product_title.clone();
                    }
                    description = if props.short_description.is_empty() {
                        props.product_description.clone()
                    } else {
                        props.short_description.clone()
                    };
                    // Heroic shows art_square on the library tile and
                    // art_cover behind the game page, which is the portrait
                    // and the wide art respectively.
                    let art = |role: &str| {
                        ROLES
                            .iter()
                            .find(|(name, _)| *name == role)
                            .and_then(|(_, purposes)| pick(&props.images, purposes))
                            .map(|image| image.absolute_uri())
                            .unwrap_or_default()
                    };
                    art_square = art("cover");
                    art_cover = art("hero");
                    if art_cover.is_empty() {
                        art_cover = art_square.clone();
                    }
                    if art_square.is_empty() {
                        art_square = art_cover.clone();
                    }
                }
            }
            Err(err) => eprintln!("could not look up {store_id} in the catalog: {err}"),
        }
    }

    let app_name = app_name(store_id.as_deref().unwrap_or(&title));
    let Some(heroic) = heroic_config_dir(config) else {
        eprintln!("could not find a Heroic configuration directory; pass --config");
        return ExitCode::FAILURE;
    };

    let launcher = if dry_run {
        source.join("xpedited-launch.sh")
    } else {
        match write_launcher(&source, &wine, exe.as_deref(), prefix.as_deref(), &title) {
            Ok(path) => path,
            Err(err) => {
                eprintln!("could not write the launcher script: {err}");
                return ExitCode::FAILURE;
            }
        }
    };

    let entry = json!({
        "runner": "sideload",
        "app_name": app_name,
        "title": title,
        "install": {
            "executable": launcher.display().to_string(),
            // Native, so that Heroic runs the script itself rather than
            // starting a second wine around the one xodus already uses.
            "platform": "linux",
            "is_dlc": false,
        },
        "folder_name": source.display().to_string(),
        "art_cover": art_cover,
        "art_square": art_square,
        "is_installed": true,
        "canRunOffline": true,
        "description": description,
    });

    let library_path = heroic.join("sideload_apps").join("library.json");
    let mut library: Value = std::fs::read_to_string(&library_path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_else(|| Value::Object(Map::new()));
    if !library.is_object() {
        library = Value::Object(Map::new());
    }
    upsert(&mut library, entry);

    if dry_run {
        println!("{}", serde_json::to_string_pretty(&library).unwrap());
        return ExitCode::SUCCESS;
    }

    if let Err(err) = std::fs::create_dir_all(library_path.parent().unwrap()) {
        eprintln!("could not create {}: {err}", library_path.display());
        return ExitCode::FAILURE;
    }

    // Heroic keeps this file in memory and rewrites it wholesale, so a write
    // underneath a running Heroic is simply lost. Say so rather than leaving
    // the user wondering where the entry went.
    let temporary = library_path.with_extension("json.tmp");
    let written = serde_json::to_string_pretty(&library)
        .map_err(std::io::Error::other)
        .and_then(|text| std::fs::write(&temporary, text))
        .and_then(|()| std::fs::rename(&temporary, &library_path));
    if let Err(err) = written {
        let _ = std::fs::remove_file(&temporary);
        eprintln!("could not update {}: {err}", library_path.display());
        return ExitCode::FAILURE;
    }

    println!("added {title} to Heroic as {app_name}");
    println!("  launcher  {}", launcher.display());
    println!("  library   {}", library_path.display());
    if art_square.is_empty() {
        println!("  no store art was found, so the tile will be blank");
    }
    println!("restart Heroic if it is running, or it will overwrite this.");
    ExitCode::SUCCESS
}

/// Write the launcher for a title that is listed but not yet on disk. The
/// first launch fetches the package; every launch after that is just a
/// launch. Heroic's sideload runner has no install step of its own - its
/// `install` is an explicit "not implemented" - so an entry has to be
/// launchable straight away or it is a dead row in the library.
fn write_catalog_launcher(
    launchers: &Path,
    store_id: &str,
    title: &str,
    games_dir: &Path,
    wine: &str,
    prefix: Option<&str>,
) -> std::io::Result<PathBuf> {
    let path = launchers.join(format!("{}.sh", app_name(store_id)));
    let cli = std::env::current_exe()
        .map(|path| path.display().to_string())
        .unwrap_or_else(|_| "xodus-cli".to_string());
    let prefix = prefix.unwrap_or("$HOME/.local/share/xpedited/prefix");

    let script = format!(
        "#!/usr/bin/env bash\n\
         # Generated by `xpedited heroic --catalog` for {title}. Safe to regenerate.\n\
         set -uo pipefail\n\
         \n\
         XPEDITED_CLI=${{XPEDITED_CLI:-{cli}}}\n\
         XPEDITED_WINE=${{XPEDITED_WINE:-{wine}}}\n\
         export WINEPREFIX=${{WINEPREFIX:-{prefix}}}\n\
         GAME_DIR={game_dir}\n\
         \n\
         # Listed before it is downloaded, so fetch it the first time. Heroic\n\
         # has no progress bar for this - as far as it knows the game is just\n\
         # slow to start - and these are multi-gigabyte downloads, so put the\n\
         # progress somewhere the player can actually see it.\n\
         # The marker keeps its old name so games downloaded before the\n\
         # rename are still recognised as downloaded.\n\
         MARKER=\"$GAME_DIR/.xodus-streaming.msixvc\"\n\
         if [ ! -e \"$MARKER\" ]; then\n\
         \x20   command -v notify-send >/dev/null &&\n\
         \x20       notify-send -a Xpedited \"Downloading {title}\" \"This runs once. The game starts when it finishes.\"\n\
         \x20\n\
         \x20   if [ -t 1 ]; then\n\
         \x20       \"$XPEDITED_CLI\" streaming {store_id} \"$GAME_DIR\"\n\
         \x20   elif term=$(command -v konsole || command -v gnome-terminal || command -v xterm); then\n\
         \x20       case ${{term##*/}} in\n\
         \x20           konsole)        \"$term\" -e \"$XPEDITED_CLI\" streaming {store_id} \"$GAME_DIR\" ;;\n\
         \x20           gnome-terminal) \"$term\" -- \"$XPEDITED_CLI\" streaming {store_id} \"$GAME_DIR\" ;;\n\
         \x20           *)              \"$term\" -e \"$XPEDITED_CLI\" streaming {store_id} \"$GAME_DIR\" ;;\n\
         \x20       esac\n\
         \x20   else\n\
         \x20       \"$XPEDITED_CLI\" streaming {store_id} \"$GAME_DIR\"\n\
         \x20   fi\n\
         \x20\n\
         \x20   # The terminal's exit code is its own, so judge by the result.\n\
         \x20   if [ ! -e \"$MARKER\" ]; then\n\
         \x20       command -v notify-send >/dev/null &&\n\
         \x20           notify-send -u critical -a Xpedited \"{title} did not download\" \"Run the launcher from a terminal to see why.\"\n\
         \x20       exit 1\n\
         \x20   fi\n\
         \x20   \"$XPEDITED_CLI\" heroic-sync >/dev/null 2>&1 || true\n\
         fi\n\
         \n\
         exec \"$XPEDITED_CLI\" run \"$GAME_DIR\" \"$XPEDITED_WINE\"\n",
        title = title,
        cli = cli,
        wine = wine,
        prefix = prefix,
        game_dir = shell_quote(&games_dir.join(store_id).display().to_string()),
        store_id = shell_quote(store_id),
    );

    std::fs::write(&path, script)?;
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))?;
    Ok(path)
}

#[allow(clippy::too_many_arguments)]
pub async fn run_catalog(
    client: &reqwest::Client,
    wine: String,
    games_dir: Option<String>,
    market: Option<String>,
    prefix: Option<String>,
    config: Option<String>,
    limit: Option<usize>,
    dry_run: bool,
) -> ExitCode {
    let market = market.unwrap_or("US".to_string());
    let home = std::env::var("HOME").unwrap_or_default();
    let games_dir = PathBuf::from(games_dir.unwrap_or_else(|| format!("{home}/Games/xodus")));
    let launchers = PathBuf::from(format!("{home}/.local/share/xpedited/launchers"));

    let ids = match xodus::api::gamepass::pc_catalog(client, &market).await {
        Ok(ids) => ids,
        Err(err) => {
            eprintln!("could not read the Game Pass catalog: {err}");
            return ExitCode::FAILURE;
        }
    };
    println!("{} titles in the PC Game Pass catalog", ids.len());

    let ids: Vec<String> = match limit {
        Some(limit) => ids.into_iter().take(limit).collect(),
        None => ids,
    };

    let Some(heroic) = heroic_config_dir(config) else {
        eprintln!("could not find a Heroic configuration directory; pass --config");
        return ExitCode::FAILURE;
    };
    let library_path = heroic.join("sideload_apps").join("library.json");
    let mut library: Value = std::fs::read_to_string(&library_path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_else(|| Value::Object(Map::new()));
    if !library.is_object() {
        library = Value::Object(Map::new());
    }

    if !dry_run {
        for dir in [&games_dir, &launchers] {
            if let Err(err) = std::fs::create_dir_all(dir) {
                eprintln!("could not create {}: {err}", dir.display());
                return ExitCode::FAILURE;
            }
        }
    }

    let languages = vec!["en-US".to_string()];

    // Fetch the catalogue once, then find out which of the products it points
    // at actually have something to download. It is one extra pass over a few
    // hundred ids, and it is the difference between a library of games and a
    // library of disappointments: Assassin's Creed and the EA Play titles
    // resolve to packages the EA app and Ubisoft Connect deliver, not to
    // anything we can fetch.
    let mut products = vec![];
    for chunk in ids.chunks(12) {
        match xodus::api::displaycatalog::find_products_by_ids(client, chunk, &market, &languages)
            .await
        {
            Ok(response) => products.extend(response.products),
            Err(_) => {
                // A batch occasionally comes back unreadable; ask for those
                // ones individually rather than lose twelve titles to it.
                for id in chunk {
                    if let Ok(response) = xodus::api::displaycatalog::find_products_by_id(
                        client,
                        id.clone(),
                        market.clone(),
                        languages.clone(),
                    )
                    .await
                    {
                        products.push(response.product);
                    }
                }
            }
        }
    }

    let mut wanted: Vec<String> = products
        .iter()
        .filter(|product| !has_desktop_package(product))
        .flat_map(satisfying_products)
        .collect();
    wanted.sort();
    wanted.dedup();

    println!("checking {} related products for a package", wanted.len());
    let mut downloadable: std::collections::HashSet<String> = std::collections::HashSet::new();
    for chunk in wanted.chunks(12) {
        if let Ok(response) =
            xodus::api::displaycatalog::find_products_by_ids(client, chunk, &market, &languages)
                .await
        {
            for product in response.products {
                if has_desktop_package(&product) {
                    downloadable.insert(product.product_id.clone());
                }
            }
        }
    }

    let mut added = 0usize;
    let mut skipped = 0usize;
    let mut installed = 0usize;
    let mut listed: std::collections::HashSet<String> = std::collections::HashSet::new();

    {
        for product in products {
            let store_id = product.product_id.clone();
            if store_id.is_empty() {
                continue;
            }

            // Listing a title we could never download is no kinder than
            // hiding one we could, so the answer is worked out rather than
            // guessed: either this product carries a Windows desktop package,
            // or one of the products that satisfies it does.
            if !has_desktop_package(&product)
                && !satisfying_products(&product)
                    .iter()
                    .any(|id| downloadable.contains(id))
            {
                skipped += 1;
                continue;
            }

            let Some(props) = product.localized_properties.first() else {
                skipped += 1;
                continue;
            };
            let title = if props.product_title.is_empty() {
                store_id.clone()
            } else {
                props.product_title.clone()
            };
            let description = if props.short_description.is_empty() {
                props.product_description.clone()
            } else {
                props.short_description.clone()
            };
            let art = |role: &str| {
                ROLES
                    .iter()
                    .find(|(name, _)| *name == role)
                    .and_then(|(_, purposes)| pick(&props.images, purposes))
                    .map(|image| image.absolute_uri())
                    .unwrap_or_default()
            };
            let mut art_square = art("cover");
            let mut art_cover = art("hero");
            if art_cover.is_empty() {
                art_cover = art_square.clone();
            }
            if art_square.is_empty() {
                art_square = art_cover.clone();
            }

            listed.insert(app_name(&store_id));
            if already_installed(&library, &app_name(&store_id)) {
                installed += 1;
                continue;
            }

            let launcher = launchers.join(format!("{}.sh", app_name(&store_id)));
            if !dry_run
                && let Err(err) = write_catalog_launcher(
                    &launchers,
                    &store_id,
                    &title,
                    &games_dir,
                    &wine,
                    prefix.as_deref(),
                )
            {
                eprintln!("could not write the launcher for {title}: {err}");
                continue;
            }

            upsert(
                &mut library,
                json!({
                    "runner": "sideload",
                    "app_name": app_name(&store_id),
                    "title": title,
                    "install": {
                        "executable": launcher.display().to_string(),
                        "platform": "linux",
                        "is_dlc": false,
                    },
                    "folder_name": games_dir.join(&store_id).display().to_string(),
                    "art_cover": art_cover,
                    "art_square": art_square,
                    // Heroic's sideload runner cannot install anything, so a
                    // row that is not "installed" can never be started. The
                    // launcher does the downloading instead.
                    "is_installed": true,
                    "canRunOffline": true,
                    "description": description,
                }),
            );
            added += 1;
        }
    }

    // An earlier pass may have listed titles this one has decided are not
    // downloadable after all. Upserting alone would leave them behind, so
    // drop ours that did not make the cut - unless the game is really on
    // disk, in which case the player has it and it stays.
    let mut pruned = 0usize;
    if let Some(games) = library["games"].as_array_mut() {
        games.retain(|game| {
            let Some(name) = game["app_name"].as_str() else {
                return true;
            };
            if !name.starts_with("xodus-") || listed.contains(name) {
                return true;
            }
            let on_disk = game["folder_name"]
                .as_str()
                .is_some_and(|folder| Path::new(folder).is_dir());
            if !on_disk {
                pruned += 1;
            }
            on_disk
        });
    }

    if dry_run {
        println!(
            "would add {added} titles, leave {installed} already on disk alone, and skip {skipped} with nothing downloadable"
        );
        return ExitCode::SUCCESS;
    }

    if let Err(err) = std::fs::create_dir_all(library_path.parent().unwrap()) {
        eprintln!("could not create {}: {err}", library_path.display());
        return ExitCode::FAILURE;
    }
    let temporary = library_path.with_extension("json.tmp");
    let written = serde_json::to_string_pretty(&library)
        .map_err(std::io::Error::other)
        .and_then(|text| std::fs::write(&temporary, text))
        .and_then(|()| std::fs::rename(&temporary, &library_path));
    if let Err(err) = written {
        let _ = std::fs::remove_file(&temporary);
        eprintln!("could not update {}: {err}", library_path.display());
        return ExitCode::FAILURE;
    }

    match sync_categories(&heroic, &library) {
        Ok((ready, pending)) => println!(
            "{ready} downloaded, {pending} will download on first play - filter by category in Heroic"
        ),
        Err(err) => eprintln!("could not update Heroic's categories: {err}"),
    }

    println!(
        "added {added} titles to Heroic; left {installed} already on disk alone, removed {pruned} no longer downloadable, skipped {skipped} with nothing downloadable"
    );
    println!("  games      {}", games_dir.display());
    println!("  launchers  {}", launchers.display());
    println!("  library    {}", library_path.display());
    println!("the first launch of a title downloads it, so give it time.");
    println!("restart Heroic if it is running, or it will overwrite this.");
    ExitCode::SUCCESS
}
