use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde_json::{Map, Value, json};

use super::metadata::{ROLES, pick};

/// Heroic keys everything off app_name and uses it as a config file name, so
/// it has to be stable across runs and safe on a filesystem. The store id is
/// both, and prefixing it keeps these apart from anything Heroic adds itself.
fn app_name(store_id: &str) -> String {
    format!("xodus-{store_id}")
}

/// The package config carries commented out examples of the very fields we
/// are looking for - LIMBO ships a `**REPLACE WITH STOREID**` placeholder -
/// so the comments have to go before anything is read out of it.
fn strip_comments(xml: &str) -> String {
    let mut out = String::with_capacity(xml.len());
    let mut rest = xml;
    while let Some(start) = rest.find("<!--") {
        out.push_str(&rest[..start]);
        match rest[start..].find("-->") {
            Some(end) => rest = &rest[start + end + 3..],
            None => return out,
        }
    }
    out.push_str(rest);
    out
}

fn tag_value(xml: &str, tag: &str) -> Option<String> {
    let open = format!("<{tag}>");
    let start = xml.find(&open)? + open.len();
    let end = xml[start..].find(&format!("</{tag}>"))?;
    Some(xml[start..start + end].trim().to_string())
}

fn attr_value(xml: &str, element: &str, attribute: &str) -> Option<String> {
    let open = format!("<{element}");
    let key = format!("{attribute}=\"");
    let mut offset = 0;

    while let Some(found) = xml[offset..].find(&open) {
        let start = offset + found;
        offset = start + open.len();

        // `<Executable` is also the start of `<ExecutableList`, so the name
        // has to end where the element name ends.
        let tail = &xml[offset..];
        if tail.chars().next().is_some_and(|c| c.is_alphanumeric()) {
            continue;
        }

        let Some(close) = tail.find('>') else { break };
        let attributes = &tail[..close];
        if let Some(value) = attributes.find(&key) {
            let value = value + key.len();
            if let Some(end) = attributes[value..].find('"') {
                return Some(attributes[value..value + end].to_string());
            }
        }
    }
    None
}

/// Packages are inconsistent about the case of this file - Wolfenstein 3D
/// ships `MicrosoftGame.config` and Minecraft `MicrosoftGame.Config` - so try
/// what is actually on disk rather than a fixed name.
fn read_game_config(source: &Path) -> Option<String> {
    let entries = std::fs::read_dir(source).ok()?;
    for entry in entries.flatten() {
        if entry
            .file_name()
            .to_string_lossy()
            .eq_ignore_ascii_case("MicrosoftGame.config")
        {
            return std::fs::read_to_string(entry.path())
                .ok()
                .map(|xml| strip_comments(&xml));
        }
    }
    None
}

/// A store id is twelve alphanumeric characters. Checking the shape keeps a
/// leftover template value out of a catalog lookup.
fn valid_store_id(value: &str) -> bool {
    value.len() == 12 && value.chars().all(|c| c.is_ascii_alphanumeric())
}

fn heroic_config_dir(explicit: Option<String>) -> Option<PathBuf> {
    if let Some(explicit) = explicit {
        return Some(PathBuf::from(explicit));
    }

    let home = PathBuf::from(std::env::var("HOME").ok()?);
    let config = std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| home.join(".config"));

    [
        config.join("heroic"),
        home.join(".var/app/com.heroicgameslauncher.hgl/config/heroic"),
    ]
    .into_iter()
    .find(|path| path.is_dir())
}

/// Heroic launches a native entry by running the executable directly, so the
/// thing it is pointed at is a script that hands the game back to xodus. It
/// lives beside the game so that Heroic's own uninstall, which deletes the
/// executable's directory, removes the right thing.
fn write_launcher(
    source: &Path,
    wine: &str,
    exe: Option<&str>,
    prefix: Option<&str>,
    title: &str,
) -> std::io::Result<PathBuf> {
    let path = source.join("xodus-launch.sh");
    let cli = std::env::current_exe()
        .map(|path| path.display().to_string())
        .unwrap_or_else(|_| "xodus-cli".to_string());
    let prefix = prefix.unwrap_or("$HOME/.local/share/xodus/prefix");

    let script = format!(
        "#!/usr/bin/env bash\n\
         # Generated by `xodus-cli heroic` for {title}. Safe to regenerate.\n\
         set -uo pipefail\n\
         \n\
         XODUS_CLI=${{XODUS_CLI:-{cli}}}\n\
         XODUS_WINE=${{XODUS_WINE:-{wine}}}\n\
         export WINEPREFIX=${{WINEPREFIX:-{prefix}}}\n\
         \n\
         exec \"$XODUS_CLI\" run {source} \"$XODUS_WINE\"{exe}\n",
        title = title,
        cli = cli,
        wine = wine,
        prefix = prefix,
        source = shell_quote(&source.display().to_string()),
        exe = exe.map_or(String::new(), |exe| format!(" -e {}", shell_quote(exe))),
    );

    std::fs::write(&path, script)?;
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))?;
    Ok(path)
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Replace this game's entry in Heroic's sideload library, keeping every
/// other entry and any field Heroic has added to ours since.
fn upsert(library: &mut Value, entry: Value) {
    let games = library
        .as_object_mut()
        .expect("library is an object")
        .entry("games")
        .or_insert_with(|| Value::Array(vec![]));
    let Some(games) = games.as_array_mut() else {
        *games = Value::Array(vec![entry]);
        return;
    };

    let name = entry["app_name"].as_str().unwrap_or_default().to_string();
    match games
        .iter_mut()
        .find(|game| game["app_name"].as_str() == Some(name.as_str()))
    {
        Some(existing) => {
            let (Some(existing), Some(entry)) = (existing.as_object_mut(), entry.as_object())
            else {
                return;
            };
            for (key, value) in entry {
                existing.insert(key.clone(), value.clone());
            }
        }
        None => games.push(entry),
    }
}

pub async fn run(
    client: &reqwest::Client,
    source: String,
    wine: String,
    exe: Option<String>,
    market: Option<String>,
    prefix: Option<String>,
    config: Option<String>,
    dry_run: bool,
) -> ExitCode {
    let source = match std::fs::canonicalize(&source) {
        Ok(source) => source,
        Err(err) => {
            eprintln!("{source}: {err}");
            return ExitCode::FAILURE;
        }
    };

    let game_config = read_game_config(&source);
    // Plenty of packages - most of the Unity ones - name no executable at
    // all. That is not a problem: only the game's own executable is kept
    // encrypted in the container, so `run` picks the right one on its own
    // when it is not told.
    let exe = exe.or_else(|| {
        game_config
            .as_deref()
            .and_then(|xml| attr_value(xml, "Executable", "Name"))
    });

    let store_id = game_config
        .as_deref()
        .and_then(|xml| tag_value(xml, "StoreId"))
        .filter(|id| valid_store_id(id));

    // The catalog is public, so art and a proper title come for free when we
    // know the store id. Without one we still have a launchable entry.
    let mut title = source
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "Xbox game".to_string());
    let mut description = String::new();
    let mut art_square = String::new();
    let mut art_cover = String::new();

    if let Some(store_id) = &store_id {
        match xodus::api::displaycatalog::find_products_by_id(
            client,
            store_id.clone(),
            market.unwrap_or("US".to_string()),
            vec!["en-US".to_string()],
        )
        .await
        {
            Ok(response) => {
                if let Some(props) = response.product.localized_properties.first() {
                    if !props.product_title.is_empty() {
                        title = props.product_title.clone();
                    }
                    description = if props.short_description.is_empty() {
                        props.product_description.clone()
                    } else {
                        props.short_description.clone()
                    };
                    // Heroic shows art_square on the library tile and
                    // art_cover behind the game page, which is the portrait
                    // and the wide art respectively.
                    let art = |role: &str| {
                        ROLES
                            .iter()
                            .find(|(name, _)| *name == role)
                            .and_then(|(_, purposes)| pick(&props.images, purposes))
                            .map(|image| image.absolute_uri())
                            .unwrap_or_default()
                    };
                    art_square = art("cover");
                    art_cover = art("hero");
                    if art_cover.is_empty() {
                        art_cover = art_square.clone();
                    }
                    if art_square.is_empty() {
                        art_square = art_cover.clone();
                    }
                }
            }
            Err(err) => eprintln!("could not look up {store_id} in the catalog: {err}"),
        }
    }

    let app_name = app_name(store_id.as_deref().unwrap_or(&title));
    let Some(heroic) = heroic_config_dir(config) else {
        eprintln!("could not find a Heroic configuration directory; pass --config");
        return ExitCode::FAILURE;
    };

    let launcher = if dry_run {
        source.join("xodus-launch.sh")
    } else {
        match write_launcher(&source, &wine, exe.as_deref(), prefix.as_deref(), &title) {
            Ok(path) => path,
            Err(err) => {
                eprintln!("could not write the launcher script: {err}");
                return ExitCode::FAILURE;
            }
        }
    };

    let entry = json!({
        "runner": "sideload",
        "app_name": app_name,
        "title": title,
        "install": {
            "executable": launcher.display().to_string(),
            // Native, so that Heroic runs the script itself rather than
            // starting a second wine around the one xodus already uses.
            "platform": "linux",
            "is_dlc": false,
        },
        "folder_name": source.display().to_string(),
        "art_cover": art_cover,
        "art_square": art_square,
        "is_installed": true,
        "canRunOffline": true,
        "description": description,
    });

    let library_path = heroic.join("sideload_apps").join("library.json");
    let mut library: Value = std::fs::read_to_string(&library_path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_else(|| Value::Object(Map::new()));
    if !library.is_object() {
        library = Value::Object(Map::new());
    }
    upsert(&mut library, entry);

    if dry_run {
        println!("{}", serde_json::to_string_pretty(&library).unwrap());
        return ExitCode::SUCCESS;
    }

    if let Err(err) = std::fs::create_dir_all(library_path.parent().unwrap()) {
        eprintln!("could not create {}: {err}", library_path.display());
        return ExitCode::FAILURE;
    }

    // Heroic keeps this file in memory and rewrites it wholesale, so a write
    // underneath a running Heroic is simply lost. Say so rather than leaving
    // the user wondering where the entry went.
    let temporary = library_path.with_extension("json.tmp");
    let written = serde_json::to_string_pretty(&library)
        .map_err(std::io::Error::other)
        .and_then(|text| std::fs::write(&temporary, text))
        .and_then(|()| std::fs::rename(&temporary, &library_path));
    if let Err(err) = written {
        let _ = std::fs::remove_file(&temporary);
        eprintln!("could not update {}: {err}", library_path.display());
        return ExitCode::FAILURE;
    }

    println!("added {title} to Heroic as {app_name}");
    println!("  launcher  {}", launcher.display());
    println!("  library   {}", library_path.display());
    if art_square.is_empty() {
        println!("  no store art was found, so the tile will be blank");
    }
    println!("restart Heroic if it is running, or it will overwrite this.");
    ExitCode::SUCCESS
}
